### ISSUE TITLE
Poor Documnetion

### ISSUE THREAD

**Issue by ali-najjar** [CesiumGS/cesium-native#1029]
Hi

I want to try implement and render the globe in qt (I mean QOpenglWidget) by cesium native
But I cant find a roadmap; and cesium native actully has a poor document
What should I do ? Where should I start for use cesium-native apis in correct way ?

**Comment by j9liu** [comment]
Hi @ali-najjar,

It looks like you posted this question on our community forum [here](https://community.cesium.com/t/rendering-cesium-in-qt-or-opengl/37123). I've responded there, so let's close this issue so we can keep the discussion in one place. Thank you!
