### ISSUE TITLE
Performance testing and optimization

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#114]
This is a time-boxed (10 days) task to examine various aspects of the cesium-native and Cesium for Unreal performance to measure where it spends its time/memory and look for ways to improve it. Including:

* Memory usage
* CPU usage
* GPU usage
* Number of tiles requests

We should look for ways to instrument the tile load pipeline in order to collect statistics, such as:

* how long tiles take to download a tile
* how long it takes to parse a glTF
* how long it takes to decode Draco buffers and images
* how long it takes to upsample tiles for raster overlays
* total time from "tile first identified as needed" to "tile ready to render"

Unreal Engine has a nice system for collecting this kind of information without a major impact on performance, but we can't easily use that from cesium-native. What can we do instead?

**Comment by jtorresfabra** [comment]
Just stumbled across this one. Just wanted to say that I hit with the stb_image slowness wall before, and the issue is even worse when running in wasm (https://github.com/CesiumGS/cesium-native/issues/76#issuecomment-744441497).

**Comment by kring** [comment]
Quick update, mostly just as an excuse to share some nifty charts...

`prepareInLoadThread` (the Unreal, non-game-thread part of preparing a glTF for rendering) is taking a surprisingly long time for the Melbourne tileset. Here's a chart of the distribution of execution times for Cesium World Terrain:
![image](https://user-images.githubusercontent.com/924374/122210809-614bee00-cee9-11eb-961a-ae29247c16e6.png)

It's produced in chrome://tracing by rubber band selecting the CWT loading processes and select `prepareInLoadThread` and then clicking the `Duration` radio button.

So it takes under 2ms on average, and the worst case is ~46ms.

Now here's the Melbourne tileset in the same run (I had Actors for both datasets):

![image](https://user-images.githubusercontent.com/924374/122211321-f18a3300-cee9-11eb-88ac-a7346449b12b.png)

Here the average is over 100ms and the longest tiles take close to a second. This is pretty surprising because the function does _not_ include:

* Any waiting for I/O or for threads to become available.
* Draco decoding.
* Image decoding.
* Creating Unreal Engine UObjects or renderer resources.

It does include physics cooking, though, so that's my best guess about what's taking all the time.

Here's the complete trace that can be loaded in chrome://tracing:
[tracer.zip](https://github.com/CesiumGS/cesium-native/files/6662692/tracer.zip)

**Comment by baothientran** [comment]
@kring Is the number for when the app in the game mode? If it’s in the editor mode, another source that can cause the slow down maybe that swapping may occur due to Garbage Collection doesn’t run on the editor. In the past, after I force gc.CollectEveryFrame 1, I can see higher frame rate in the editor

**Comment by kring** [comment]
That's a release build running in the editor. It's basically just the initial load of the two tilesets, on a 32GB system, so there shouldn't be any swapping. But I'll check it out to be sure.

**Comment by kring** [comment]
PhysX cooking averages 46ms per Melbourne tile. Compared to 1.3ms per CWT tile.
Computing tangents with MikkTSpace averages 32ms per Melbourne tile. Compared to 0.9ms per CWT tile.

Are the Melbourne tiles just that much more complex?

**Comment by kring** [comment]
On the MikkTSpace side, I think we can gain substantial performance just by... not doing it.

Tangents are required when we're using a normal map, because normal maps are expressed in tanget space. I _thought_ that they were required more generally, because there doesn't appear to be a way to exclude tangents entirely from a static mesh. But if we just set them to the zero vector (which is a _lot_ faster than running MikkTSpace), I can't see any rendering differences at all. We should probably add an "Always Include Tangents" option, though, in case users are using a custom material that requires them.

A very nice side benefit of not generating tangents  is that a model that has normals but doesn't have a normal _map_ will no longer need to have vertices duplicated to avoid sharing them between triangles. Which means less memory usage and less GPU load. Models without normals will still need to have vertices duplicated, though, so that we can generate flat normals as required by the glTF spec.

**Comment by baothientran** [comment]
Do you think by any chance Unreal generate even normal for us too? It would be interesting to see if lightning change at all if we remove normal. If it does, we may get more performance by only using indexed triangle instead of flattening them out currently

**Comment by kring** [comment]
We can't _remove_ normals, they're always in the static mesh. Same with tangents. But we can set the normals to some constant value or whatever instead of computing them properly. When we do that, the lighting falls apart, as you'd expect. AFAIK there's no way to have UE generate them for us. Even if there were, I'd be nervous that it would do it in the game thread and tank performance, like it does when physics meshes are missing (only in the editor, though...outside the editor there's just no collision at all).

It might be nice to have an option that says "when normals are missing, ignore the glTF spec's requirement of flat normals and just compute a normal per vertex from the weighted average of the faces that share that vertex." That should be much more performant and I suspect it'd be fine (or maybe even better) for 90% of cases.

**Comment by kring** [comment]
I wrote some new issues based on the work done here:
CesiumGS/cesium-unreal#509
CesiumGS/cesium-unreal#510
CesiumGS/cesium-unreal#511
CesiumGS/cesium-unreal#512

Performance is a never-ending task, but I think we can close this and write new and more specific performance-releated issues as necessary.
