### ISSUE TITLE
Discussion about the traversal process

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#126]
The current traversal procedure of tiles is - virtually by definition - the most simple traversal process that will ever exist. 

In the future, there will be ...

- additional culling criteria. 
- additional visibility checks. 
- additional flags that can be switched on or off. 
- additional tile types and providers. 
- refinements for the refinements. 
- extensions for the prioriztations of tile loading. 
- additional information (statistics, performance measures) that have to be collected during the traversal. 
- additional operations that are supposed to be done during the traversal. 
- additional strategies for the order in which the children of a tile will be visited. 

Each of these could offer great options for new features and improvements. But it also means that the complexity of the traversal **can** only increase (and I'd say it's bound to increase *dramatically*). If there is no clear separation of concerns, no abstraction, and no clear, high-level outline for the process itself and the state transitions, the state space will face a combinatorial explosion. 

But even though the current state is the most simple state that will ever exist, it's already ... complicated. 

---

An aside: It may sound like an inappropriate and/or bold claim, but I'm pretty sure that we're already at a point where nobody knows exactly what happens during the traversal. One example for what caused my concerns here is that the traversal starts with this method:

    Tileset::TraversalDetails Tileset::_visitTileIfNeeded(
        const FrameState& frameState,
        uint32_t depth,
        bool ancestorMeetsSse,
        Tile& tile,
        ViewUpdateResult& result

I tried to figure out the meaning of the `ancestorMeetsSse` flag. And I think this is essentially not possible. (Spoiler alert: It certainly does not say whether an ancestor meets the SSE). And when it's impossible to clearly state the conditions under which this flag, which is passed into the top-level-traversal call (!) and passed along (and changed occasionally...) is `true` or `false`, then that's not good: Any unit-test that is supposed to do something that is even indirectly affected by this flag could just capture the current state, but not say whether the current state is "right" or "wrong". 

---

From an idealistic perspective, I wondered whether it could be possible to move towards a state where the traversal process looks more like this pseudocode...:

    ViewUpdateResult updateView(ViewState viewState) {
        TraversalResult traversalResult = traverse(root, TraversalState(viewState, frameNumber));

        addTilesToLoadQueues(traversalResult.tilesToLoad);
        passTilesToRenderer(traversalResult.tilesToRender);
        removeTilesFromRenderer(traversalResult.tilesToRemove);
        
        return ViewUpdateResult(traversalResult);
    }
    TraversalResult traverse(Tile tile, TraversalState traversalState) {
        TraversalResult traversalResult(traversalState);
        
        if (shouldNotBeVisitedForWhateverReason(tile)) {
            traversalResult.visited = 0;
            return traversalResult;
        }
        if (!isVisible(tile, traversalState)) {
            traversalResult.culled = 1;
            butMaybeLoadSiblingsOf(tile, traversalResult);
            return traversalResult;
        }
        if (shouldBeLoaded(tile, traversalState)) {
            load(tile, traversalResult);
        }
        if (shouldBeRendered(tile, traversalState)) {
            render(tile, traversalResult);
        }
        if (shouldBeRefined(tile, traversalState)) {
            refine(tile, traversalResult);
        }
        if (shouldBeCoarsened(tile, traversalState)) {
            removeChildren(tile, traversalResult);
        }
        for (Tile child : tile.children) {
            TraversalState childTraversalState = traversalState.withDepthPlusOne();
            TraversalResult childTraversalResult = traverse(child, childTraversalState);
            traversalResult.combineWith(childTraversalResult);
        }
        return traversalResult;
    }
    
Yes, I know that it cannot be that simple. But some rough (!) ideas reflected by this pseudocode being

- There is a top-level `updateView` function. It receives the `FrameState` that is *constant* throughout the traveral. It returns the `ViewUpdateResult` that summarizes the result of the whole traversal, and contains *exactly* the information that is supposed to be available for clients (that's roughly as in the current implementation)
- There is an internal `traverse` method (which might even be encapuslated in some `TilesetVisitor`, FWIW). It receieves a `TraversalState` that is *constant for that particular branch*. It returns the `TraversalResult` which summarizes the information that was accumulated while traversing *that particular branch*.
- The `TraversalResult` of consists of the information for the given tile, *combined* with the traversal results for all its children
- The conditions for when a tile `shouldBeLoaded`, `shouldBeRendered`, `shouldBeRefined` ... are clearly stated (in the documentation of the respective methods). More broadly speaking, the goal would be to assign clear, concise meanings to terms like "visiting", "loading", "rendering", "refining"
- It should be clear where *state transitions* take place. 

The state transitions (reflected with the `LoadState` and `TileSelectionState::Result`) already are complex, and every attempt to simplify this will require diligence, a deep understanding of the process, and the goals. But for example, stating the criterion for "rendering a tile" with a method like

    bool shouldBeRendered(Tile tile, TraversalState traversalState) {
        if (traversalState.parentWasRendered) {
            return false;
        }
        if (!tile.isLoaded()) {
            return false;
        }
        if (isAnyLoading(tile.children)) {
            return false;
        }
        return true;
    }
    
and establishing a clear connection between the decision of whether a tile should be rendered and the *state change*, as in 

    if (!tile.rendered) {
        if (shouldBeRendered(tile)) {
            render(tile);
            tile.rendered = true;
        }
    }

could allow to *document* the meaning of "rendering", and the unit tests could be straightforward, as in

    assertFalse(shouldBeRendered(unloadedTile, traversalState));
    assertFalse(shouldBeRendered(tileWithLoadingChildren, traversalState));
    assertFalse(shouldBeRendered(tile, traversalStateWithRenderedParent));
    assertTrue (shouldBeRendered(tile, traversalState));

or
    
    assertFalse(tile.rendered);
    render(tile);
    assertTrue (tile.rendered);

In contrast to that, and referring to the (maybe overly specific) example above: The `ancestorMeetsSse` flag will (among other things) affect whether a tile will be "rendered". And whether it is `true` depends (among other things) on whether a *child* of the tile is "not renderable". And a child tile is "renderable" when...

    this->getState() >= LoadState::ContentLoaded &&
    (!this->_pContent || this->_pContent->model.has_value()) &&
    !std::any_of(this->_rasterTiles.begin(), this->_rasterTiles.end(), [](const RasterMappedTo3DTile& rasterTile) {
        return rasterTile.getLoadingTile() && rasterTile.getLoadingTile()->getState() == RasterOverlayTile::LoadState::Loading;
    });
    
I cannot imagine how to write a sensible test, stating the conditions under which a certain tile will be "rendered", and achieving a sensible coverage of the state space that determines whether these conditions are actually met or not.

--- 

I know that there is nothing harder than trying to make complex things simple. But I think it is crucial to at least try to work towards such a simpler, clearer state. I also know that what I wrote here may appear to be naive or overly idealistic, and it does not allow deriving immediate actions. But maybe others can share their thoughts or ideas about the possible paths forward.

**Comment by kring** [comment]
@javagl what do you think we should do with this issue? Here are some actions I can think of that we might derive from it:

1. Have more detailed discussions about how tileset traversal works and how its implementation can be improved. I think we might be near the limit of what we can achieve on GitHub, though, and maybe need a live conversation and a whiteboard to really take it further.
2. Refactor the tileset traversal for clarity, without changing how it works. This is safer now that @baothientran has implemented some unit tests for it.
3. Write some documentation of how the tileset traversal works. I'd probably be best placed to do this.
4. Start designing a next-gen, pluggable selection/loading algorithm. A lot of thought would need to be given to requirements, first. i.e., what problems are we actually trying to solve. And it would need to be closely aligned with the implicit tiling / VR tile selection work happening elsewhere in Cesium.

Any others? I think we can write actionable issues for 2 and 3. 1 could be worth doing but doesn't need an issue. I'm hesitant to embark on 4 at the moment, and I don't think we need an issue for it in the meantime, but might change my tune in the next few months.

**Comment by javagl** [comment]
As mentioned above: 

> On the one hand, the process is complicated, and I don't understand it. On the other hand, making specific suggestions (on a level where they would allow to derive actual action patterns (as in "code changes")) would require a deep understanding.

Or to put it that way: I don't think that these 4 points can be strictly separated. The next-gen traversal (4) might be the ultimate (and somewhat abstract) goal, but placing a bunch of engineers into a room with the task "Solve this problem, and report when you're done" is not gonna fly, for many obvious reasons. Regarding the documentation (3): There are different *kinds* of documentation (one could call them "levels"). "Low-level" documentation (`// Comments` and `/* doxygen */`) only make sense when they convey relevant knowledge. (I remember writing the API docs, and felt uncomfortable when I had to "document" functions like `queueLoadOfChildrenRequiredForRefinement()` with a comment like `/* Queue load of children required for refinement */, without really saying anything...). Creating a "high-level" documentation (on the level or a markdown file) for *existing* code (in hindsight) is hard, and almost certainly not really useful: While one might have an idealized idea about the process on the level of nice diagrams with boxes and arrows, this rarely tells the truth. I mean, I could document the current process, and still wouldn't know how to fix a certain bug...

---

However, **tl;dr**, to have the chance to derive some actions: 

I think that refactoring for clarity (2) is a necessity, if anything substantial is going to happen with the code at all. 

This requires an understanding that could be achieved with (1), adding documentation (3), and keeping in mind the next-gen traversal (4) (because that's the ultimate goal that we should be moving *towards* - in steps, because there is not other option). 

I tried to make some suggestions above, about "what the code could look like" after the refactoring. Other suggestions may be a bit hidden, in https://github.com/CesiumGS/cesium-native/pull/94#discussion_r547997889 , slack comments, and the branch that I mentioned in an [earlier comment](https://github.com/CesiumGS/cesium-native/issues/126#issuecomment-774504271) (and that's likely very out of sync in the meantime). 

But to summarize a few points that I'd consider as crucial:

- Shorter methods that do *one* thing only, with and fewer parameters (parameter objects where necessary)
- Get rid of global state accesses and global state changes during traversal, i.e. the `this->options` and the three load queues....
- Make the *state* clearer. When a `Tile` is in a certain `Tile::LoadState` (or a `RasterOverlayTile` is in a certain `RasterOverlayTile::LoadState`...), or a tile is in a certain `TileSelectionState`, it must be clear
  - How did the tile get into this state?
  - What does that state say about the properties/fields of the tile?
  - What are the conditions for a tile going into another state?
  - What is the (in the best case: *single*) method that changes that state?
  - Which thread is causing the state change? 

  (This seemingly covers only the part that is stored as an explicit `state` variable, but also refers to "state-like functions", like `isRenderable`...)

---

If this is desired, some of that *could* be extracted into issues (like "Avoid accessing the options during the traversal"), but depending on the granularity and the actual task, this may not always be nice pairs of "An issue" and "A PR that fixes that issue".

**Comment by kring** [comment]
> Creating a "high-level" documentation (on the level or a markdown file) for existing code (in hindsight) is hard, and almost certainly not really useful: While one might have an idealized idea about the process on the level of nice diagrams with boxes and arrows, this rarely tells the truth.

I don't think I agree here. I think the high-level documentation would be very useful and truthful enough, even if it misses some corner cases. Obviously it needs to be written by someone that already understands the algorithm pretty deeply.

> Shorter methods that do one thing only, with and fewer parameters (parameter objects where necessary)

Shorter methods can absolutely be an aid to understanding, but not always. Certainly, when we can break out a bit of code into a short method with a clear name that will tell anyone reading it exactly what that method does, such that someone reading code that _uses_ that method will immediately know what's happening there and won't have to go look at the new method, we're winning! We've just made our code easier to read.

On the other hand, if we break out a bit of code into a new method, but it's difficult to capture what that method does with a succinct name, we've actually _hurt_ readability even though we've replaced one long method with two shorter ones. Anyone reading the code will need to jump around to understand what is happening, rather than reading a linear process in a linear fashion.

Similarly, parameter objects are great when we can capture a group of parameters together in a meaningful abstraction. But taking ten parameters and turning them into ten fields in a struct actually hurts readability rather than helping it, because someone reading the code will need to jump to the struct to see what is being passed.

My point is, this is a balance. More, shorter methods is _not_ always better than than a smaller number of longer ones. The goal should be clarity not method brevity. I'm definitely not claiming the selection algorithm has this right everywhere, of course.

> Get rid of global state accesses and global state changes during traversal, i.e. the this->options and the three load queues....

Why is it a problem to access `options` during the traversal? What would you do instead, pass the traversal-affecting options (which is most of them) through the recursive function calls?

> Make the state clearer.

Sounds great. I've thought about having each state of a tile be represented by a separate object, e.g. in a std::variant or something. So that the current state is explicit, and the data associated with the tile in each state is clear as well.

Or perhaps take a more data-oriented design approach where a "tile" is just an ID, and there are separate slices of data associated with that ID based on its current state(s).

There are lots of details to work out, though.

> I think that refactoring for clarity (2) is a necessity, if anything substantial is going to happen with the code at all.
> 
> This requires an understanding that could be achieved with (1), adding documentation (3), and keeping in mind the next-gen traversal (4) (because that's the ultimate goal that we should be moving towards - in steps, because there is not other option).

This sounds like a good plan. Some thoughts:
1. I should write the high-level documentation, and I think it would be unwise to start significant refactoring before this is in place.
2. I can't tell you exactly how the refactoring should proceed, but once you (or whoever) has done something I'm likely to have opinions on it, and it'll probably involve some rework and be really annoying (e.g. my rant about method length above). Sorry about that.
3. Beyond basic refactoring for clarity, I think we need to figure out some concrete, long term goals/requirements. For example, refactoring to allow different parts of the process to be pluggable/customizable could be really useful, or it could just be a bunch of architecture astronautics that makes that code more complicated and slower without any tangible benefits.
4. As always, we should consider the priority of this relative to everything else we have going on. My gut is that unless we're planning to make significant changes to the selection algorith in the short/medium term (see 3 above), or think we could get a significant performance improvement, or it would help fix significant bugs lurking beneath the surface (like the missing tile flicker foir instance), it's hard to justify major changes to it. Our energy is far better invested delivering features that our users really need, rather than making the selection algorithm prettier.

**Comment by javagl** [comment]
>  if we break out a bit of code into a new method, but it's difficult to capture what that method does with a succinct name, we've actually hurt readability
> 
> Similarly, parameter objects are great when we can capture a group of parameters together in a meaningful abstraction. But taking ten parameters and turning them into ten fields in a struct actually hurts readability 

If it's difficult to capture what the method does with a succinct name, or (as a special form of that) if it's difficult to "summarize" (and *name*) the data that a method operates on, then that's a clear indicator (for me) that something is wrong. And that's one of the reasons why writing doxgen docs is good, not only for the *reader*, but also for the *writer*: If a class/method cannot be described with few, clear, concise statemends, then that's the point where I tend to take a step back, squint my eyes, ask myself "So what's *really* going on there?", and take the refactoring to the next coarser of granularity.

But moving back to the actionable items:

> I think the high-level documentation would be very useful and truthful enough,

It **can** be, for sure. I just mentioned that because 1. I've seen enough "diagrams", where people summarized complex applications (literally on the level of `[Server] <--- communicates with ---> [Client]`), and 2. the devil is in the detail. 

The "detail" here refers to the states and state transitions. I'm not sure whether I understood the part of the `std::variant` correctly. It sounds like

    class Tile {
        class TileBeforeLoading { Request request; }
        class TileAfterLoading { Response response; }
          
        std::variant<TileBeforeLoading, TileAfterLoading> state;
    }

but that's probably not what you meant. (I still consider `variant` to be clumsy and UN-object-oriented in many ways...)

> Why is it a problem to access options during the traversal? What would you do instead, pass the traversal-affecting options (which is most of them) through the recursive function calls?

I think we already talked quickly (but only in Slack, IIRC) about separating 1. the tileset and 2. the "traverser". I have a "strictly pragmatic" view on *what a class should be*, and *what belongs into the class*. And from that viewpoint, I'd say that something like `bool preloadAncestors` (and in fact, most other `options`) is simply *not* part of the Tileset (and its state). The tileset is the tileset. Whether or not ancestors should be preloaded is a question for the *traversal*.

And on a lower level: Whenever I see a `bool` that governs part of a *behavior*, then I *strongly* consider to model that via polymorphism. Using that specific example, in an overly suggestive form: I could not introduce a `bool preloadAncestors` without considering the alternative of having some `preloaders.push_back(new AncestorPreloader())`. I know, it sounds a bit controversial, but I can elaborate that if necessary. Taken too far, this can lead to "over-engineering". But the right amount of that makes the difference between "writing code that does something" and *engineering*.


The summary:

> 2. ... probably involve some rework and be really annoying (e.g. my rant about method length above). Sorry about that.

When I have the choice between ...

- a complex change/PR being merged after 10 mMinutes, with the comment "LGTM"
- a profound, technical discussion about the pros and cons of the chosen approach, and possible alternatives

... then I'd not only *prefer*, but in some way actually *expect* the latter. Good software does not "happen automatically".

> 4. ... Our energy is far better invested delivering features that our users really need, rather than making the selection algorithm prettier.

**If** a refactoring/simplification can lead to a state where the question of "Why does this tile flicker?" can be answered with "The reason can be A or B, and we can find the definite answer by setting a breakpoint", instead of spending several days with black-box-debugging, then that's a definite win. And **if** it brings us closer to a state where addressing one of the bullet points that I mentioned in the first post does *not* cause us to start sweating and think "Oh dear, we have to change something in the traversal!" (c.f. [Lava Flow](https://en.wikipedia.org/wiki/Lava_flow_(programming))), but allows us to confidently ask: "Yeah, which additional feature do you want?", then that's also a win.

**Comment by javagl** [comment]
The fact that the `ITileExcluder` just randomly popped up [in this commit](https://github.com/CesiumGS/cesium-native/commit/92c79297abce20cbed8c131209cd35143a5fbf4c) directly to `main`, without any PR, planning or discussion, is very, very unfortunate. 

---

First of all: Handling the list of excluders via the `TilesetOptions` is _just not good_, period. The `TilesetOptions` are an anti-object-oriented structure that should be abandoned as soon as possible. It is a "global state" that combines things that are **completely unrelated**. Having random accesses to different aspects of state, scattered through the whole traversal, makes the code far more complex than it should be, and severely reduces the maintainability and extensibility. 

---

Where and how this excluder is queried is something that should be thought through more carefully. One could certainly make a point for having `ITileExcluder` instances that are queried during the traversal, and others that are only queried only **once**, when a tile is first encountered. (They could then store the result of the query, maybe in some sort of `map<TileID, bool>` (aka `set<TileID>`)). This could be done to avoid doing the (possibly complex) exclusion check repeatedly. And the polygon-based check is [*tremendously* complex](https://github.com/CesiumGS/cesium-native/blob/fc3f11dd2bfd670a5c4fba1bcfa71f263c47742a/Cesium3DTilesSelection/src/TileUtilities.cpp#L43), so that should at least be considered.

<sup>Yes: What happens when the polygons change? Then the stored exclusion results will have to be invalidated. This has to be kept in mind, but should not be a blocker</sup>

---

The `ITileExcluder` interface itself should have existed before even the first line of traversal code was written. The whole traversal is about "including" or "excluding" tiles, so even with **zero** knowledge about what has to be implemented there, one could define this interface and the code of the traversal based on that class. This could include what I'd call some "default infrastructure classes" (like a `CompoundTileExcluder` that combines several delegates, and returns `true`/`false` depending on the results of the delegates).  And when examining that more closely, one might notice that the frustum culling is an `ITileExcluder`. And the fog is an `ITileExcluder`. And every other culling criterion is an `ITileExcluder`. 

<sup>And sure, sometimes there may be additional information required, like the `ViewState`. Then introduce a `IViewBasedTileExcluder` and head on...</sup>

---

If this was crafted more carefully, then the `cullingChecks.push_back(myNewCriterion)` that I sketched in [a comment more than half a year ago](https://github.com/CesiumGS/cesium-native/issues/126#issuecomment-774699319) could already be in reach. Now, we can do a `tilesetOptions.excluders.push_back(rasterizedPolygonsTileExcluder)`, but it is offered in a form that will increase the efforts for everybody who wants to bring in further improvements or generalizations here, and make future refactorings _more necessary_ and _more complex_ at the same time.

**Comment by kring** [comment]
> The fact that the ITileExcluder just randomly popped up in this commit directly to main

No, it was added in this PR:
https://github.com/CesiumGS/cesium-native/pull/326

Needless to say I disagree with most of this, but thanks for your thoughts.

**Comment by kring** [comment]
Lots of interesting thoughts here, but since in its current form it's not something that can ever be actioned / resolved, I'm going to close this.

**Comment by javagl** [comment]
Quoting from [another comment](https://github.com/CesiumGS/cesium-native/issues/216#issuecomment-1120622954) : 

> Everyone is encouraged to improve the quality of the code along these dimensions whenever they run into an opportunity to do so

When there is the chance to do a "small" improvement that opens rooms for further exploration (like replacing inlined code for one particular way of computing the SSE with an interface like `SssCuller` that could eventually allow the `cullingChecks.push_back(myNewCriterion)` that I mentioned earlier), then this <strike>could</strike> should be done.
