### ISSUE TITLE
Create a command-line application for testing

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#199]
There should be an option to have something like a
```
int main(int argc, char** argv) {
    ...
    std::string tilesetUrl = readFrom(argv);
    ...
    Cesium3DTiles::Tileset tileset(externals, tilesetUrl, options);
    ...
    tileset.updateView(viewState);
    ...
    return 0;
}
```
in order to quickly an easily read a tileset from disc and test and debug (i.e. set breakpoints in) the `cesium-native` part. For all bugs and issues that are in `cesium-native`, the Unreal Editor adds unnecessary hassle and overhead when it comes to testing and debugging. It should be possible to run basic tests by just starting something like

    cesium-native-test.exe -input C:/Data/Issue123/tileset.json

 **WITHOUT** the Unreal Editor being wrapped around all that. 

(I created something like this a few months ago, with some results summarized in https://github.com/CesiumGS/cesium-native/pull/127 , but there have been many incompatible changes in the meantime. Also, the exact way of how this may be added, also considering the CMake build, has to be decided upon).

**Comment by kring** [comment]
@javagl why not use a Catch2 test for this, rather than a separate main/executable? There's a VS Code plugin called "CMake Test Explorer" that makes it easy to run and debug individual tests. I'm sure there's a way to do it in regular Visual Studio, too.

**Comment by javagl** [comment]
It might be possible to extend the test infrastructure for that, but I wonder how one would sensibly achieve a state where one could just load a tileset that some user has sent as a ZIP file. (I'd even say that it should be possible to create a `TilesetExternals` without external dependencies - i.e. there should be default implementations for all its elements - but that may just be a technical detail).  I just wanted to mention that idea, considering that we'll certainly receive tileset files that we need to load and debug. But my hacky standalone application is good enough for my purposes, and if nobody else needs such a `just-load-that-tileset.exe`, we can also omit it.
