### ISSUE TITLE
Code style for functions in general, and lambdas in particular

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#216]
I originally wrote this as a [comment to the initial coding guidelines PR](https://github.com/CesiumGS/cesium-native/pull/82#issuecomment-770951333), but it may be worth addressing that as a dedicated issue:

There are several places where deeply nested, complex lambdas are passed back and forth and executed with multiple threads. One example was already quoted in the aforementioned comment. I recently stumbled over similar patterns in the `Connection` class, where up to 10 parameters are passed through two nested lambdas, once by reference and once by copy. Similarly, the lambdas that are passed to the `AsyncSystem::thenInMainThread/thenInWorkerThread` functions are capturing random context and sometimes have hundreds of lines with indentation levels of 8 and beyond. 

This has to be broken down into smaller blocks, with *names*, *documentation*, and *comments*. The names should tell the reader what is done there. The documentation should explain what the captured values/arguments are and how they are used. The comments should say how the states of these objects may be modified, and (importantly) *on which thread* things are supposed to happen. 

I think this can largely be achieved by extending the guidelines with hints like

- Functions [SHOULD](https://tools.ietf.org/html/rfc2119) have fewer than 50 lines
- Lambdas SHOULD have fewer than 10 lines
- Functions SHOULD receive fewer than 5 arguments
- The indentation level SHOULD be less than 4
- Functions (also `private` ones) should have short comments, stating the purpose of the functions, preconditions and postconditions, state changes, and maybe hints about thread safety

with exceptions being applied judiciously.

If nobody disagrees, I'd consider this issue not only as a place for discussion about small extensions to the coding guidelines, but also as the basis for a review/PR where excessively long, deeply nested and undocumented lambdas are converted into functions accordingy. I know that this will be challenging and error-prone, due to subtle differences between lambda captures and function argument evaluation. But particularly for the case of lambdas that are executed on different threads and that have long by-ref/pointer capture lists, it is crucial to know how the catures/arguments will be used or possibly modified.

**Comment by kring** [comment]
Everyone is encouraged to improve the quality of the code along these dimensions whenever they run into an opportunity to do so, but we don't need a dedicated effort or an issue to track it. Closing.
