### ISSUE TITLE
`npm run format` can break doxygen `{@link foobar}` comments

### ISSUE THREAD

**Issue by Samulus** [CesiumGS/cesium-native#218]
I noticed this while fixing the documentation on my recently merged PR. You have to take special care to avoid clang-format from wrapping a `{@link foobar}` declaration to another line (this breaks the rendered doxygen html)

**Comment by kring** [comment]
Oh geeze that's really annoying. Any ideas on how to fix it, short of disabling comment reflow entirely?

**Comment by Samulus** [comment]
https://stackoverflow.com/a/51913607 I found this, I'll give it a try and make a trivial PR if it fixes it.

**Comment by javagl** [comment]
I fixed the comments that had been wrong in https://github.com/CesiumGS/cesium-native/pull/234 

For avoiding that problem in the future, we considered different options. The fallback would have been to disable formatting for comments altogether. But the "least invasive" solution was (c.f. the link by @Samulus ) to use a `CommentPragmas` at https://github.com/CesiumGS/cesium-native/pull/234/files#diff-1026e0038b722990204a42bed8a6f7c0ec2302aa79e3fad1959d62ba968edfa2R37 

`CommentPragmas: '{.*}'`

this will cause `clang-format` to **NOT** break lines that contain `{@link SomeClass}` links.

An aside: I also checked whether there...

    /**
     * ...may be a problem with some line that is long `and where the part that would end up on the next line was backticked`
     */

and these are broken, as in

    /**
     * ...may be a problem with some line that is long `and where the part that would 
     * end up on the next line was backticked`
     */

**but** doxygen can cope with that, and the output still looks right.

**Comment by javagl** [comment]
@Samulus The `CommentPragmas` now prevent `clang-format` from breaking lines that contain `{@link SomeClass}` links. It would be nicer if there was the option to *only* treat the `{@link SomeClass}` like "**one** word", but there doesn't seem to be such fine-grained control. 
I assume that this can be closed, and will do that soon.
