### ISSUE TITLE
Investigate the use of Conan instead of submodules for third-party dependencies

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#230]
https://conan.io/

It's already being used for some Cesium-internal C++ projects.

The main goal being to reduce cesium-native git clone and compilation time.

**Comment by baothientran** [comment]
rapidjson's release version is 4 years ago and we are using the sha in their main branch. I created an issue on their repo to ask if they can do another release/tag version https://github.com/Tencent/rapidjson/issues/1896

**Comment by lilleyse** [comment]
> rapidjson's release version is 4 years ago and we are using the sha in their main branch. I created an issue on their repo to ask if they can do another release/tag version Tencent/rapidjson#1896

We can use the `rapidjson/cci.20211112` version in conan in the meantime - https://conan.io/center/rapidjson

**Comment by kring** [comment]
Closing this one because it's a duplicate of #248.
