### ISSUE TITLE
Review the namespace structure

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#241]
There currently is some inconsistency regarding namespaces. Some functions are written as `private` `static` helper functions, that could go into an anonymous namespace. Some structures, specifically `struct`s that are used to ~"bundle some information and pass it around privately", are in the main namespace in public headers, and could or should go into an anonymous namespace, or into an `impl` namespace.

There is certainly some inspiration to be taken from things like boost or ... well, the standard library. My not-so-deeply technical classification, roughly aligned with that, would be: to 1.) put things into anonymous namespaces by default 2.) put them into the public namespace only when it's absolutely sure that this is supposed to be public forever, and 1.5.) move things into an `impl` namespace (maybe even with `"...Impl.h"` and `"...Impl.cpp"`) when something has to be accessible internally.

I'm not deeply familiar with the best practices for large-scale C++ projects (and by "best practices", I mean things that have been done consistently in other projects, with clear technical justifications, and helped the projects to stand the test of time, in terms of API stability and maintainability). Maybe people with more experience want to chime in here.

**Comment by kring** [comment]
This more or less describes what we're doing. In general, we should be thoughtful about what we expose publicly, and avoid exposing implementation details. Where we've gotten that wrong, we should fix it or write an issue for it. I don't think we can do much with a general issue like this one, though, so I'm closing it.
