### ISSUE TITLE
Export targets in Cmake configuration

### ISSUE THREAD

**Issue by jtorresfabra** [CesiumGS/cesium-native#247]
Would be great if cesium-native export the targets in the cmake configuration so for an external application can be as easy as find_package(cesium-native) and then link against CesiumNative::CesiumNative or each individual library like CesiumNative::CesiumGeospatial. 

CC: https://github.com/CesiumGS/cesium-native/issues/231

**Comment by kring** [comment]
Duplicate of #231.
