### ISSUE TITLE
Visual Studio exception handling warning C4530.

### ISSUE THREAD

**Issue by tfiner** [CesiumGS/cesium-native#250]
While building using VS 2017, I noticed a ton of these warnings:
`warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc`

The fix is easy, just add /EHsc to the target_compile_options under the MSVC conditional in CMakeLists.txt.

Otherwise, the lack of unwind semantics (destructors not getting called) will ruin someone's day the first exception that occurs.

**Comment by kring** [comment]
CC #212

**Comment by tfiner** [comment]
Funny enough, I tried a different tack and cloned this repo right from VS 2019 and used its internal CMake compatibility to build it.  I didn't see the warning when I built this way, my guess is (I didn't dig into it) that they appended the flag.

**Comment by kring** [comment]
I'm not sure exactly what was happening here, but we build every commit with VS2017 and haven't seen this warning. So I'm going to close this, but please reopen if you still have concerns.
