### ISSUE TITLE
Add support for multiple layers of quantized mesh

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cesium-native#253]
CesiumJS has the support for multiple layers in the layer.json for Quantized mesh. It will allow client to use their own terrain data on top of our CWT.

**Comment by kring** [comment]
Yes that looks like the same problem @gabrielamelian.

**Comment by argallegos** [comment]
[Another user asking for this on the forum](https://community.cesium.com/t/how-to-use-dem-tiff-files-in-cesium-for-unreal/17752/7) - looks like this might need to be done before users can import custom terrain from ion.
