### ISSUE TITLE
Extend Gltf generator tool into generic Json schema generator tool

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cesium-native#270]
I just stumble `quicktype` library [here](https://github.com/quicktype/quicktype) that can generate C++ classes from json schema along with serializer and deserializer. You can try it online here https://app.quicktype.io/. However, the code it generates is quite poor, for example: a `double` property is turned into `std::shared_ptr<double>`, or it uses `regex` header. Given that our gltf generator tool may almost work with any json file, I think we should extend it to generate C++ code with a generic json schema and add support for both serialization and deserialization too. Bonus if we can generate validator from the schema as well

**Comment by kring** [comment]
Yeah the glTF generator was definitely intended to be generic, with 3D Tiles in mind in particular, though obviously that vision isn't fully realized. It does require the particular JSON Schema version that the glTF schema uses, but I think 3D Tiles uses the same one so that should be a good fit.

**Comment by kring** [comment]
The same code is now used to generate classes for 3D Tiles, too.
