### ISSUE TITLE
3D Tiles Serializer

### ISSUE THREAD

**Issue by IanLilleyT** [CesiumGS/cesium-native#278]
There should be a 3D Tiles serializer for Cesium Native that goes between C++ and JSON. It would function very similarly to the glTF serializer and could probably use the same `JSON schema <-> C++` generator located [here](https://github.com/CesiumGS/cesium-native/tree/main/tools/generate-gltf-classes), but with a few tweaks, as brought up in https://github.com/CesiumGS/cesium-native/issues/270. Note that right now only the glTF reader is generated automatically, not the writer (see https://github.com/CesiumGS/cesium-native/issues/228 for generating glTF writer).

The 3D Tiles serializer would not be responsible for `pnts`, `b3dm`, `glTF`, or any other external buffer data. It would only do the `tileset.json`. One challenge will be external tilesets. For now, we could keep it simple and let the caller create the external tilesets themselves (possibly using the 3D Tiles serializer).

Ultimately we'll want this to work with 3D Tiles exensions too, similar to how extensions are done in the glTF, but getting it working with the base 3D Tiles schema is a good start. I attached a small sample tileset below.

Resources:
3D Tiles schemas: https://github.com/CesiumGS/3d-tiles/tree/master/specification/schema
3D Tiles extensions: https://github.com/CesiumGS/3d-tiles/blob/3d-tiles-next/3D_TILES_NEXT.md
3D Tiles Metadata extension: https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/extensions/3DTILES_metadata/1.0.0/schema
Sample data: [sign.zip](https://github.com/CesiumGS/cesium-native/files/6770340/sign.zip)

[Localhost sandcastle for viewing sample data](http://localhost:8080/Apps/Sandcastle/index.html#c=bZBBSwMxEIX/StjLbqEkVS9St0WoR0GhRS97SZOxO5pNlmR2Syv+d5PdFko1lzAv8817mV561iPswbMFs7BnKwjYNfxt0IpcDeXKWZJowedT9l1Zxgi8j8Krdz1q8PMzpjxIgnfnjd6MLcVkWtmfyUNl+2hFaCAARa/RlAcFFnjrsUHCHgKXWhcXOcbr7mkzgsXg3nnD5iyvidq5EMYpaWoXaH4/m92KQJJQiYA7K052/DM4m6cYKcdZbB1aWhnX6XUtNdodl0Rgu4g7GxOS7yDFHoMenWs2rjjBaU42zcpABwPLlCmdR2xa5ynlKzgXBE1r4jqC2HbqKzqqEBKYWktxiZYae4Z6UWVX+64ypowMIb58dMas8QhVtixF7P+DGjf84qUHb+QhtdU3y+dR5JyXIpb/k+Sc2Up/NfkX)

CC @baothientran @kring

**Comment by krupkad** [comment]
@lilleyse 
Current status of this work (as of Aug 11):
- "Groundwork" is merged (#299, #301)
- Writer is under review (#306)
- Reader PR is open (#308)

**Comment by kring** [comment]
This has been implemented.
