### ISSUE TITLE
Discussion about the prominent use of `Future`

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#303]
I noticed a pattern in the use of the `AsyncSystem`/`AssetAccessor` of which I'm not sure whether it is the best path to follow. (And I have doubts that it is, that's why I'm writing this issue). The pattern can roughly be described as "building asynchronicity into functions by default". 

---

I mainly noticed this in the context of [`RasterOverlayTileProvider::loadTileImage`](https://github.com/CesiumGS/cesium-native/blob/38a1faea125990208c2d3d6647f3c78c85e71bfa/Cesium3DTiles/include/Cesium3DTiles/RasterOverlayTileProvider.h#L369). This function returns a `Future<LoadedRasterOverlayImage>`, thus, having this "built-in" asynchonicity. The consequence is that each implementor needs the `AsyncSystem`, even if there is no asynchronicity involved. For example, the `PlaceholderTileProvider` receives the `AsyncSystem` to just call `createResolvedFuture`. Other implementations call `runInWorkerThread`, which seems to be "synchronous" depending on the calling thread. Everybody who wants to do something substantial will do this via `assetAccessor->requestAsset(asyncSystem, ...)`.

So at the surface (meaning the API level here), this shows up as "passing the `AsyncSystem` and `AssetAccessor` around (sometimes even when it is not necessary)". The core of this pattern is, as pseudocode:

```
Future<Output> loadData(Input input) {
    return assetAccessor->request(input.url)
       .then([response]{
           return computeOutputFrom(response.data);
       });
}
```
(where the `computeOutputFrom` usually is a loooong lambda with looong capture lists, sometimes, containing the `AssetAccessor` and `AsyncSystem` again...).

I think that this makes the overall structure, method signatures, comments, and unit tests, far more complicated than they should be. 

---

A little more abstractly, this pattern can be described as using a JavaScript-ish approach of using `Promise` (aka `Future`) everywhere, and then assembling promise chains. (Which, IMHO, is only an undesirable artifact of JavaScripts single-threadedness. In our case this eventually caused the necessity for things like `AsyncSystem::all` (and maybe `::any` at some later point), `catchImmediately`, and `runInWorkerThread`, in order to cope with the undesired `Future`-ness of the intermediate results...)

**Far** more abstractly: The _decision_ of whether a certain operation should happen synchronously or asynchronously (or on which thread they are supposed to happen) could (and in most cases: should) be left to the caller. Imagine a function that computes the sum of the elements of a vector:
```
double computeSum(vector<double> numbers) { ... }
```
Why not write this as
```
Future<double> computeSum(vector<double> numbers) { ... }
```
in order to allow the computation to be done asynchronously? The answer is simple: *If* the user wants to do this asynchronously, then he can do this. 
```
Future<double> futureResult = runOnThread([numbers]{ 
   return computeSum(numbers); 
});
```

---

Now, the controversial part:
 
Applied to some of the places in the current code, this would mean that the pseudocode from above should be

```
// Blocks the calling thread
Output loadData(Input input) {
    Future<Output> future assetAccessor->request(input.url)
       .then([response]{
           return computeOutputFrom(response.data);
       });
    return await(future);
}
```
And if somebody wants to *not* block and/or execute this on whatever other thread, it can be called as
```
Future<Output> futureOutput = runOnThread([url]{ 
   return loadData(url); 
});
futureOutput.thenInWhateverThread([output] { ... });
```
(This can optionally be wrapped into a convenience function in some cases). 

---

I know that one could be tempted to argue that ~"network requests are _inherently_ asynchronous". But they are not. One can block the calling thread until the result is there. That's usually not what one wants to do, but that is a decision about an aspect that is _orthogonal_ to the actual operation that is performed. I also know that no change is gonna happen here: The pattern is already too prominent to ever be removed. But I think that it increases the complexity, and mainly wanted to mention that I think that it could tremendously increase clarity if we more strictly separated between a _function_ (which has one input, one output, and does something synchronously) and the question on which thread this function should be executed.

**Comment by kring** [comment]
Your proposal would make our plugin _far_ less efficient. In fact, it might break Unreal Engine completely.  Do not do this.

Tasks for the worker thread are dispatched to the Unreal Engine task graph. This system is meant for short-lived operations, and the documentation explicitly says they should not block. If we dispatch tasks that block on network requests, the task graph would grind to a halt. Unreal Engine wouldn't be able to do the little bits of background work it needs in its normal course of gameplay and rendering, and we'd see major stutters or pauses.

Ok, what if we don't use the task graph? We could dispatch background work to our own thread pool instead. But we're still burning threads to do no useful work (other than block waiting for the network), so sizing that thread pool is going to be a challenge. If it's too small, it will get clogged up with network requests and other work won't be able to proceed. If it's too big, we create a ton of operating system threads, which are a finite resource with significant cost.

Fundamentally, `requestAsset` is an asynchronous operation. If it's presented that way (i.e. returns a Future) and you want to wait for it synchronously, no problem: just called `.wait()` on the future. But if it were instead presented as a synchronous operation, the only way to deal with it asynchronously is by burning a thread. There is almost zero advantage (and massive disadvantage) to hiding the asynchronous nature of this behind a blocking method call.

Of course, where an operation (like your `computeOutputFrom`) is useful or likely to be reused outside the continuation, it should be a regular synchronous method. In rare cases, a method like that will sometimes be synchronous and sometimes asynchronous, but that's not really a problem. It's a feature of the interface (e.g. `loadData` in your example) that the polymorphic operation is _allowed_ to be asynchronous. If it happens to not be, wrapping up a result in an already-resolved Future is easy. Again, delegate that synchronous work to a truly synchronous method if it's of any value to do so.

**Comment by javagl** [comment]
Maybe the "controversial" part is what you referred to as a "proposal". And I probably didn't describe that very well. Of course, the tasks in the task graph should **not** be blocking, and all this would/should **not** have any impact on performance (but only on architecture).  

Synchronous functions can be changed into asynchronous ones (returning a `Future`) by executing them on a different thread. Of course, this raises that exact questions that you already alluded to: *Which* thread? Is it from a pool? How large is that pool? Who is doing the scheduling? But one could argue that right now, we're avoiding these questions by saying "Yeah, let's set `maximumSimultaneousTileLoads=20`, hope that this makes sense, and hope that the Unreal task scheduler does the right thing". 

To emphasize that: That's not a bad thing to do! It's great when one does *not* have to ask low-level questions, and can focus on the more architectural parts. 

But that may raise other questions, and most imporantly: It does not free us from the burden of thinking about the granularity of tasks. And it's probably not a good thing to "bake" a certain granularity into the architecture. For example, I think that there once was a ~"performance issue" discovered during the tracing experiments, where - iff I understood and remember this correctly, and correct me if I'm wrong - the pattern of

    Future<Result> futureResult = requestSomething()
        .thenInMainThread(doSomeTrivialStep)
        .thenInMainThread(doSomeOtherTrivialStep)
        .thenInMainThread(doYetAnotherTrivialStep);

caused the delays between being scheduled and being executed to be "accumulated", and where a pattern of 

    Future<Result> futureResult = requestSomething()
        .thenInMainThread({
            doSomeTrivialStep();
            doSomeOtherTrivialStep();
            return doYetAnotherTrivialStep();
        });

would have been better. 

All this is related to the crucial question: **Who** decides at **which** point and **how** a certain "task" is "worthy" of being executed asynchronously? (C.f. the `computeSum` example from the first comment. When this is "built in" into the architecture, then each change may imply a refactoring).

---

One aspect of the discussion here could provocatively be phrased as: If we rely on someone else taking care of all this, why is the `AsyncSystem` so prominently appearing everywhere? You mentioned:

> ... operation is _allowed_ to be asynchronous. If it happens to not be, wrapping up a result in an already-resolved Future is easy.

Not really, because creating the resolved `Future` requires the `AsyncSystem`, even though it is not really "required" - it is only required for possible continuations. All this would be a different story if there was a `static` function akin to `make_ready_future` of `std`, and continuations could be attached to that (maybe or maybe not passing in the `AsyncSystem`). Roughly, in pseudocode:

    class SomeClass {
        AsyncSystem asyncSystem; // Passed in, in constructor....

        Future<Result> computeFutureResult() {
            return this->asyncSystem.createResolvedFuture(fixedResult);
        }
    }

    // Call site:
    Future<Result> futureResult = someClass.computeFutureResult();
    Future<ProcessedResult> futureProcessedResult = 
        futureResult.thenInMainThread(resultProcessor);

vs.

    class SomeClass {
        // No asyncSystem instance is required here!
        Future<Result> computeFutureResult() {
            return AsyncSystem::createResolvedFuture(fixedResult);
        }
    }

The question is then: What could be done at the call site **iff** there should be a continuation? There are different options...

    Future<Result> futureResult = someClass.computeFutureResult();
   
    // Option 1: Pass the AsyncSystem that should be used for the thenInMainThread call:
    futureResult.thenInMainThread(asyncSystem, resultProcessor);

    // Option 2: Offer a function in the AsyncSystem for continuing a given Future:
    asyncSystem.continueInMainThread(futureResult, resultProcessor);

As an attempt to "summarize that point of criticism": I think that the fact that the `Future` "owns" an `AsyncSystem` (in that it is required for creating a `Future`) has some drawbacks.

---

Another point is related to this:

> Of course, where an operation (like your computeOutputFrom) is useful or likely to be reused outside the continuation, it should be a regular synchronous method. 

Usually, this is not the case. But it should **not only** be done when something is likely to be reused elsewhere. Doing this is an integral part of a clear structure and design. But I won't repeat what I said about "long lambdas with long capture lists (but without comments for that capture lists)" here, because that's already summarized in https://github.com/CesiumGS/cesium-native/issues/216 . 

--- 

I'd actually like to avoid toooo specific examples here, but maybe one example can help: I tried to understand what `QuadtreeRasterOverlayTileProvider::loadTileImage` does, and think that the fact that the asynchronicity is "smeared" over the call chain of 
```
loadTileImage(...) {
  mapRasterTilesToGeometryTile(...) {
    getQuadtreeTile(...) {
      loadQuadtreeTileImage(...) {
        loadTileImageFromUrl(...) {
          this->getAssetAccessor()->requestAsset(...)
        }.then...
      }.then...
    }.then...
  }.then...
}
```
makes it *tremendously* hard to answer the questions: What is happening here? When is it happening? What is happening on which thread? Is there a https://en.wikipedia.org/wiki/Sequence_diagram for all that? (Or why is there none? Because it's so complicated and might change frequently in an unforeseeable way? Yes, that's the point...)

Specifically: The `QuadtreeRasterOverlayTileProvider::mapRasterTilesToGeometryTile` function contains >250 lines that are totally unrelated to futures, and have nothing to do with asynchronicity. But eventually, it calls `getQuadtreeTile`, which returns a future...
```
std::vector<CesiumAsync::SharedFuture<LoadedQuadtreeImage>>
QuadtreeRasterOverlayTileProvider::mapRasterTilesToGeometryTile(
    const CesiumGeometry::Rectangle& geometryRectangle,
    double targetGeometricError) {
  std::vector<CesiumAsync::SharedFuture<LoadedQuadtreeImage>> result;

  ...
  // 250 lines of code omitted here...
  ...
  {  
      CesiumAsync::SharedFuture<LoadedQuadtreeImage> pTile =
          this->getQuadtreeTile(QuadtreeTileID(imageryLevel, i, j));

      result.emplace_back(pTile);
    }
  }
  return result; 
}
```
This is an example where I'd **strongly** recommend to refactor this into two functions, one which is "synchronous", and one which is "asynchronous": 

One function does the actual ("synchronous") work:
```
std::vector<QuadtreeTileID> computeTileIdsToMap(
    const CesiumGeometry::Rectangle& geometryRectangle,
    double targetGeometricError) {
  std::vector<QuadtreeTileID> result;

  ...
  // 250 lines of code omitted here...
  ...
  {  
      result.emplace_back(QuadtreeTileID(imageryLevel, i, j));
    }
  }
  return result; 
}
```
(this one could be covered with a unit test then - wouldn't that be great?)

The other function does the async stuff:
```
std::vector<CesiumAsync::SharedFuture<LoadedQuadtreeImage>>
QuadtreeRasterOverlayTileProvider::doAllTheseRequests(vector<QuadtreeTileID> tileIds) {
  std::vector<CesiumAsync::SharedFuture<LoadedQuadtreeImage>> result;
  for (QuadtreeTileId id : tileIds) {
    CesiumAsync::SharedFuture<LoadedQuadtreeImage> pTile =
      this->getQuadtreeTile(QuadtreeTileID(imageryLevel, i, j));
    result.emplace_back(pTile);
  }
  return result;
}
```
With the (obvious?) advantage that this function can **either** return a `vector<Future>`, or encapsulate another `all` call and return a `Future<vector>`: It might be better to do any main-thread tasks that have to be done on each result element **not** by dispatching a new `thenInMainThread` on *each* of them, but with a **single** `thenInMainThread` that operates on a *vector* of results. (And as a remark that I do **not only** say in order to convince you: This may sometimes also be better for performance" ;-) )

--- 

But again: This last example is only one specific instance of the general pattern of overly prominent "promise-chains" and "granularity baked into architecture" that I noticed....

**Comment by kring** [comment]
I think that Futures are an excellent way to manage concurrency, and that passing around an AsyncSystem is a necessary evil because making the system "ambient" would be much worse for a variety of reasons.

However, the general suggestion here to separate the synchronous and the asynchronous work into separate functions is good, and the specific example in `QuadtreeRasterOverlayTileProvider::mapRasterTilesToGeometryTile` is excellent.

I'm going to close this issue, but also write an issue for the specific case. And we should keep an eye out for similar opportunities elsewhere.
