### ISSUE TITLE
Link errors with LLD when building shared libraries

### ISSUE THREAD

**Issue by ebatsin** [CesiumGS/cesium-native#309]
When I build the library using the BUILD_SHARED_LIBS cmake option, I get errors during the linking phase.

OS: Ubuntu 20.10
CC: clang 12.0.1
CXX: clang++ 12.0.1
Linker: LLD 12.0.1
build: Ninja

The issue seems to come from the following libraries which are still built STATIC:
 - spdlog (can be changed by setting SPDLOG_BUILD_SHARED to ON, but it should be automatic)
 - sqlite3 (hardcoded as STATIC)
 - modp_x64 (hardoded as STATIC)

A sample from the errors:
```
ld: error: can't create dynamic relocation R_X86_64_32S against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in extern/modp_b64/libmodp_b64.a(modp_b64.cc.o)
>>> referenced by modp_b64.cc
>>>               modp_b64.cc.o:(modp_b64_decode) in archive extern/modp_b64/libmodp_b64.a
```

I'm not an expert in linking errors, but right here I think LLD is right and the 3 libraries should be built as shared when cesium-native is built as a shared library.

**Comment by baothientran** [comment]
Hi @ebatsin building shared library option is currently not very well tested. Using static library is recommended at the moment

**Comment by ebatsin** [comment]
Ok, thanks for the quick answer. I'll use static for the time being.
