### ISSUE TITLE
The glTF content cannot be written with glTF writer

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#311]
<sup>Edited based on Kevins comment</sup>

The [`GltfContent`](https://github.com/CesiumGS/cesium-native/blob/2848ea62d406f21e70d32c0d75696df1b5602ad2/Cesium3DTilesSelection/src/GltfContent.cpp#L45) class and the [`QuantizedMeshContent`](https://github.com/CesiumGS/cesium-native/blob/2848ea62d406f21e70d32c0d75696df1b5602ad2/Cesium3DTilesSelection/src/QuantizedMeshContent.cpp#L1167) extend the glTF model with an `extras` entry that contains a string value:

    loadedModel.model.value().extras["Cesium3DTilesSelection_TileUrl"] = url;

The current [`Writer`](https://github.com/CesiumGS/cesium-native/blob/2848ea62d406f21e70d32c0d75696df1b5602ad2/CesiumGltfWriter/src/Writer.cpp#L114) tries to write these extras, it crashes (although the code in [`JsonObjectWriter`](https://github.com/CesiumGS/cesium-native/blob/2848ea62d406f21e70d32c0d75696df1b5602ad2/CesiumJsonWriter/src/JsonObjectWriter.cpp#L90) **looks** like this case should be handled...).

**Comment by kring** [comment]
> As best practice, extras should be an Object rather than a primitive value for best portability.

I read that as "the entire `extras` property value should be an object" rather than "every property inside `extras` should have an object for a value." So by my reading, `"extras": { "Cesium3DTilesSelection_TileUrl": "whatever" }` is fine. Certainly agree it shouldn't crash either way, though.

**Comment by javagl** [comment]
@kring You're right, and what I wrote there initially was remarkably nonsensical. Updated the post accordingly.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium-native/pull/416
