### ISSUE TITLE
External tilesets don't work right with enableFrustumCulling=false and enforceCulledScreenSpaceError=false

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#314]
Originally reported here with Cesium OSM Buildings, which uses external tilesets extensively:
https://community.cesium.com/t/runtime-created-cesium-tileset-with-material-osm-buildings-for-example-doesnt-render/14834/2

In the tile selection algorithm, we treat external tilesets as if they have a really huge geometric error. This guarantees that we never select them, but instead always refine past them. At least, it usually does.

A problem comes up when enableFrustumCulling is set to false. In this scenario, tiles that would otherwise be culled will be included in the render list. When enforceCulledScreenSpaceError is also false, we also will not (ever!) refine such tiles. And this is true even for external tilesets with their huge geometric error. Thus, we'll end up selecting an external tileset for rendering, even though it's not a thing we can render.

Now this alone wouldn't be a _huge_ problem. It would just be a tile in the render list without any renderable content and we could just ignore it. But because `_meetsSse` is returning true for these culled external tileset tiles (and this is the _only_ situation in which it will), we add it to the render list with `_renderInnerTile`. And `_renderInnerTile` will note that the tile's `isRenderable` method returned false (which is fair enough, it's not renderable). Because this tile isn't renderable, and never has been, the next level up in the selection traversal will kick this tile _and its siblings_ out of the render list, waiting for them all to become renderable, presumably by further loading. But an external tileset will never become renderable no matter how long we wait for it to load.

End result: we don't render this whole branch of the tile tree with these settings.

**Comment by javagl** [comment]
It may not strictly be necessary, but the keywords reminded me of the discussion around https://github.com/CesiumGS/cesium-native/issues/126#issuecomment-774352476 , so having this cross-ref here might be helpful in the future.
