### ISSUE TITLE
Write documentation for cesium-native's `AsyncSystem`

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-native#329]
Once the [clipping PR](#326) goes into main, the `./doc/threading.md` document will have been deleted. Was it out-of-date or was the removal otherwise necessary for some reason? For reference here is a permalink to the original `threading.md`: https://github.com/CesiumGS/cesium-native/blob/580beec2190755b9e5871d3d70d6d9f2b71f79e8/doc/threading.md

**Comment by kring** [comment]
The old threading.md was really old and completely wrong. We really should have an updated version, though, so I'll change this issue to request that.

**Comment by j9liu** [comment]
I tweaked the title to more generally encompass the `AsyncSystem` in cesium-native, though I imagine that multithreading will be part of that explanation.
