### ISSUE TITLE
Assertion failure in upgradeBatchTable when using cmpt tileset

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-native#341]
This does not seem to happen for tilesets with regular b3dms, only cmpt tilesets.

![cmpt-warning](https://user-images.githubusercontent.com/6706316/132603955-487d30bf-602b-4a61-9e04-84c6d8af2eca.jpg)

**Comment by kring** [comment]
@nithinp7 do you happen to remember which cmpt you were using when you ran into this? If not, perhaps we close it until we see it again.
