### ISSUE TITLE
Consider being more graceful for missing geometric error

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#343]
The error that was reported in [this forum thread](https://community.cesium.com/t/tileset-cpp-786-tile-did-not-contain-a-geometricerror/15196), saying

> "Tile did not contain a geometricError"

seems to appear for tilesets that are generated by some third-party tools. 

(I saw that error occasionally for user-provided tilesets, and can try to investigate which tool may be the culprit here).

As mentioned in the forum, the error message is from [this line](https://github.com/CesiumGS/cesium-native/blob/fc3f11dd2bfd670a5c4fba1bcfa71f263c47742a/Cesium3DTilesSelection/src/Tileset.cpp#L783). And the tileset is indeed invalid, because the [3d tiles specification](https://github.com/CesiumGS/3d-tiles/tree/main/specification#tileset) declares the `geometricError` to be *required*.

**But...** ... as much as I'm a fan of strict and clean specifications, this could be a corner case. For comparison, [CesiumJS](https://github.com/CesiumGS/cesium/blob/1837859300e61ae2ea1bc0e3832923f87e752fed/Source/Scene/Cesium3DTile.js#L138) handles this case more gracefully, by using the geometric error of the parent and only printing a warning.

I think that a similar approach could make sense for `cesium-native` as well. Whether the error of the parent should be used, or some "arbitrary" value, has to be decided. But I think that a missing geometric error should not cause the whole thing to "just do nothing". It should print a prominent, bold and clear 

> **WARNING: The tileset is invalid, because the tile XYZ does not contain a geometric error!!!**

but could try to do *something* reasonable beyond that...

**Comment by kring** [comment]
This was fixed in #441.
