### ISSUE TITLE
Should enum string value comparisons be case-sensitive?

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#345]
Again, sparked by a [forum thread](https://community.cesium.com/t/add-3dtiles-gltf1-0/15171) where [this check in `Tileset.cpp`](https://github.com/CesiumGS/cesium-native/blob/fc3f11dd2bfd670a5c4fba1bcfa71f263c47742a/Cesium3DTilesSelection/src/Tileset.cpp#L809) causes the error message

> Tile contained an unknown refine value: replace

I'd say: **Yes**, the comparison should be case-*sensitive*. A tileset with `"refine" : "replace"` should be considered to be invalid, but I wanted to bring it up.

---

EDIT:

Just for reference: [In CesiumJS, `"replace"` is allowed](https://github.com/CesiumGS/cesium/blob/1837859300e61ae2ea1bc0e3832923f87e752fed/Source/Scene/Cesium3DTile.js#L148), but causes a warning. Surprisingly, something like `"RePlace"` would **not** print a warning, but silently be accepted... (why?)

**Comment by kring** [comment]
We should:
1) check the value against the proper case, use it if we find a match.
2) try a case-insensitive comparison, log a warning and use it if we find a match.
