### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by lihengxin** [CesiumGS/cesium-native#346]
![image](https://user-images.githubusercontent.com/22095590/133364329-54611f91-a63e-4300-ae43-d1f2b8b0e976.png)    

i changed the version of node-sass and sass-loader ，but the error is also here。

**Comment by kring** [comment]
@lihengxin cesium-native doesn't use node-sass. Did you mean to submit this issue to the CesiumJS repo? https://github.com/CesiumGS/cesium
