### ISSUE TITLE
Add support for 3DTiles_implicit_tiling extension

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#353]
https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/extensions/3DTILES_implicit_tiling

I think this extension should integrate pretty nicely with the implicit tiling support already in cesium-native. In short:

* When parsing tileset.json, we should look for an `3DTILES_implicit_tiling` extension on the tile. Such a tile is known as an "implicit root".
* When we see one, we should create a new `ImplicitTilingContext` for it and arrange for the tile's content URI to be the root subtree URI. `ImplicitTilingContext` needs to be extended to capture more of the extension. In particular, it needs to capture the subtree URI, `subtreeLevels`, and `maximumLevel`.
* When loadContent is invoked on the implicit root, we load the subtree URI and populate the `availableTileRectangles` of the `TileContentLoadResult`. Or - more likely - we'll need to define an alternative way to describe availability if the extension's availability can't be easily presented as `availableTileRectangles`. The availability in `TileContentLoadResult` gets copied into the `ImplicitTilingContext` in `Tile::update`.
* Any time we want to traverse past a tile with no children, we check if the children are available implicitly and create them if so. Actually, we already do this, but we need to extend the existing logic to also load a new subtree file when needed. The easiest way to do that will be by creating a new tile with the subtree as its content.

That's a really quick and dirty summary, but hopefully enough to get you started @nithinp7 and I'll try to flesh it out a bit more tomorrow.

**Comment by lilleyse** [comment]
See https://github.com/CesiumGS/3d-tiles/pull/487 for a recent addition to the spec to specify geometric error at per-tile granularity.

Also check out https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/specification/Metadata/Semantics - there are ways to override the default implicit tiling bounding volumes using per-tile metadata.
