### ISSUE TITLE
Code generator does not properly handle keyword-named properties

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#356]
Certain JSON schemas define properties that have names like `"class"` (for example, the [EXT_feature_metadata](https://github.com/kring/glTF/blob/metadata-schema-cleanup/extensions/2.0/Vendor/EXT_feature_metadata/1.0.0/schema/featureTable.schema.json#L7) that is _currently_ used as the input for the generator). 

The code generator apparently tries to solve the resulting problems by renaming these reserved words and appending the string `Property` to the name. However, this is not properly taken into account in the *reader* classes. For example, [the reader](https://github.com/CesiumGS/cesium-native/blob/main/CesiumGltfReader/generated/GeneratedJsonHandlers.cpp#L468) now **seems** to expect the string `classProperty` in the JSON input, even though it will only find `class` there.

I extended the respective test case in https://github.com/CesiumGS/cesium-native/tree/keyword-named-properties-test-2 , which shows that even though it _should_ read the value `"tree"` into the `featureTables["tree"].classProperty` , this property has no value. (When this issue is addressed, the test cases should be extended further, but this change shows the _basic_ issue)

**Comment by nithinp7** [comment]
@kring iirc you fixed this at some point right? Especially considering we now have EXT_feature_metadata auto-generated and working correctly. Closing this, reopen if I'm mistaken.

**Comment by kring** [comment]
Both the readers and writers look to be correctly generated now. For example, in the writer for `MetadataEntity`:

```
jsonWriter.Key("class");
writeJson(obj.classProperty, jsonWriter, context);
```

And in the reader:

```
if ("class"s == str)
  return property("class", this->_classProperty, o.classProperty);
```

So I'm closing this. We can deal with the more evil scenario if and when we have a spec that does something like that.
