### ISSUE TITLE
Add support for the 3DTILES_bounding_volume_S2 extension

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#364]
https://github.com/CesiumGS/3d-tiles/tree/3d-tiles-next/extensions/3DTILES_bounding_volume_S2

This builds on #355.

We'll need:
* A new `S2BoundingVolume`, and to include it in the `BoundingVolume` variant.
* A new `S2TileID` in the TileID variant.
* The implicit tiling code will need to know how to subdivide S2TileIDs in addition to quadtrees and octrees.
* For tile selection, we'll need to be able to cull the new bounding volume against the frustum and to compute the distance to it from the camera. Look to the CesiumJS implementation and to https://github.com/google/s2geometry for inspiration. Worst case scenario, we can compute an `OrientedBoundingBox` from the S2 volume and use that for culling and distance checks, similar to what we do for `BoundingRegion`.

**Comment by nithinp7** [comment]
Finished after #387 and #390.
