### ISSUE TITLE
wrong parameter type

### ISSUE THREAD

**Issue by MarsQiu** [CesiumGS/cesium-native#430]
https://github.com/CesiumGS/cesium-native/blob/71c680e89b7d113de68e3369eebdb502514505df/CesiumIonClient/src/Connection.cpp#L143

这里参数类型不正确，应该是
```C++
redirectPath.c_str(),
```

**Comment by kring** [comment]
English translation:
> The parameter type here is incorrect, it should be

It depends what version of cpp-httplib you're using. This library was updated in #409, and the code was changed accordingly. You probably need to update your submodules:

```
git submodule update --init --recursive
```

Closing this because I don't think there's anything to change in cesium-native.
