### ISSUE TITLE
RAPIDJSON_ASSERT failure when writing model.extras from CesiumWorldTerrain

### ISSUE THREAD

**Issue by ZackOfAllTrades** [CesiumGS/cesium-native#438]
Im trying to serialize the gltf model of a CesiumWorldTerrain tile 
WriteModelResult result = CesiumGltf::writeModelAsEmbeddedBytes(loadResult->model.value(), {});

Writer.cpp line 118 fails RAPIDJSON_ASSERT when trying to write extras.

Cesium3DTiles_TileUrl, https://assets.cesium.com/1/0/1/0.terrain?v=1.2.0&extensions=octvertexnormals-metadata
gltfUpAxis, 1

**Comment by kring** [comment]
@joseph-kaile you've been working in this area recently, so do you mind taking a look at this issue?

**Comment by joseph-kaile** [comment]
Hello, @ZackOfAllTrades. It looks like you are using an older version. The new release has an improved writer than fixed this bug. However, you can fix the current code by adding this line of code (right above line 118 of Writer.cpp)

```
if (!model.extras.empty()) {
    writer->Key("extras");     // <-------
    CesiumJsonWriter::writeJsonValue(model.extras, *writer);
  }
  ```
and it should fix the problem. I hope this helps.

**Comment by ZackOfAllTrades** [comment]
thank you!
