### ISSUE TITLE
Use child tile bounding volumes to cull parent tiles

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#506]
> Instead of culling terrain/buildings/etc with the tile's OBB, use the union of the children's OBBs. It will be more precise but will have more operations. Perhaps use spatial coherence to minimize the number of checks. 

As originally mentioned here https://github.com/CesiumGS/cesium/issues/2861 and implemented in CesiumJS here https://github.com/CesiumGS/cesium/pull/4978.

**Comment by nithinp7** [comment]
Culling with children BVs where possible was implemented for both frustum and occlusion culling in #492.
