### ISSUE TITLE
Layer.json terrain breaks after Cesium ion token expiration

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#551]
After CesiumGS/cesium-native#508, `CesiumIonTilesetLoader` handles an HTTP 401 from a tile content loading request by attempting to refresh the Cesium ion token. So far, so good. The problem is that it doesn't also do this for the layer.json request. This is usually not a problem because the layer.json is requested first thing, before the token could possibly expire. However, the Cesium ion asset endpoint response (which is where the token comes from) is cached across Tilesets. So the following results in a broken Tileset:

1. Create a Tileset for, say, Cesium World Terrain.
2. Wait for the token to expire (1 hour?)
3. Delete the Tileset without loading any new tiles.
4. Create a new Cesium World Terrain tileset.

The new tileset in step 4 will reuse the asset endpoint response with the expired token to attempt to download layer.json. It will fail with a 401, and give up without refreshing the token. I don't think there's any way to recover from this other than by restarting the application.

I don't know offhand if we have the same problem when downloading the root tileset.json, or if it's specific to layer.json. It's also possible that we had this bug before CesiumGS/cesium-native#508, too.

**Comment by kring** [comment]
Forum post mentioning the same or a closely related problem:
https://community.cesium.com/t/401-error-loading-tiles/20119/2

**Comment by baothientran** [comment]
This will happens with other resources too I think, e.g Subtree, glTF images, buffers, Raster Overlay, etc. I think a better solution is to construct `CesiumIonAssetAccessor` for ion only that intercepts any request to ion and automatically refresh the token when receiving 401. The `CesiumIonAssetAccessor` will be constructed when someone passes an ion ID and token to construct an ion-related object, so in this case that will be `TilesetContentLoader` and `RasterOverlay`

**Comment by kring** [comment]
Do you know if this is a regression with the loader refactoring? If so, we need to fix it before this week's release. But if it's not new... well, we should still fix it, but it's not quite as urgent.

**Comment by baothientran** [comment]
I think it happens before too I think, so not a regression

**Comment by nithinp7** [comment]
I ran into this 2-3 times this week and each time only CWT was effected. I don't recall this happening before, definitely not in a way which would break the tileset until a full app restart happened.

**Comment by kring** [comment]
Do either of you think you might have time to fix this today so we can include it in the release? Bao's suggestion of decorator'ing the accessor with a CesiumIonAssetAccessor sounds reasonable, but that sounds like a bigger refactoring. I suspect it'll be reasonably straightforward to just handle it directly in CesiumIonTilesetLoader.
