### ISSUE TITLE
There seems to be a bug in TestSubtreeAvailability?

### ISSUE THREAD

**Issue by insar-dev** [CesiumGS/cesium-native#587]
I think that bufferSize should be (1 + 4 + 16 + ...+ maxTiles) / 8.
For example,  for  3 levels tree, there are 21 tiles, bufferSize should be 3 NOT 2.

![image](https://user-images.githubusercontent.com/1676595/212537374-f4f250f1-cc31-4e50-be9c-45e9dcdab26f.png)

**Comment by insar-dev** [comment]
I think  std::ceil(maxTiles / 8)  is wrong too, it should be   std::ceil(maxTiles / 8.0) 
8 -----> 8.0

**Comment by kring** [comment]
Thanks @insar-dev, I agree. The `3DTILES_implicit_tiling` spec has formulas that can be used to compute the necessary values:
https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling#availability-bitstream-lengths

Would you be interested in opening a pull request with the fix?

**Comment by insar-dev** [comment]
@kring i have committed pull request.

**Comment by kring** [comment]
Re-opening this until #588 is merged.
