### ISSUE TITLE
Issues when reading `.gltf` with draco

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#629]
When using the glTF loader to load a `.glTF` file that uses draco compression, then the line https://github.com/CesiumGS/cesium-native/blob/f27532c25d4dad4cbd4cdc17d4c69b60f7ee5cce/CesiumGltfReader/src/decodeDraco.cpp#L53 causes a warning to be issued:  The `buffer.cesium.data.size()` is `0` at this point, because the buffer URI is not resolved.

(Note that this is not the case for `.glb` files with draco, because the buffer is already resolved there).

From what I saw from quickly skimming over the code, this is **not** only an issue of an unnecesary warning: I think that the `return nullptr` there causes the model to not contain the decoded data at all (but only some fallback values). But that may have to be investigated in more detail.

**Comment by timoore** [comment]
See #610 which addresses this problem.

**Comment by lilleyse** [comment]
I ran into this as well. I opened a separate issue before realizing it was a duplicate: https://github.com/CesiumGS/cesium-native/issues/743

**Comment by javagl** [comment]
Note that this _might_ be fixed by https://github.com/CesiumGS/cesium-native/pull/610 (althugh I haven't tried it out with that exact branch yet)

**Comment by javagl** [comment]
From a quick test, this seems to be resolved by https://github.com/CesiumGS/cesium-native/pull/610 when explicitly loading the `.gltf` file with `loadGltf`.
