### ISSUE TITLE
Add a function to compute the terrain height at a point

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-native#636]
Similar to CesiumJS's `sampleTerrainMostDetailed`.

**Comment by gmlsw** [comment]
when to update this?

**Comment by kring** [comment]
This is currently no update. It remains something we want to do soon but we're not working on it yet. We will post here when anything changes.

**Comment by LiuWenKaiGitHub** [comment]
Hello, has this function been updated?

**Comment by gmlsw** [comment]
When will the functions for obtaining terrain height be updated in cesium for unreal like the sampleTerrain and sampleTerrainMostDetailed functions in cesiumjs

**Comment by kring** [comment]
As I said above, we'll post here when anything changes. Asking about it in the meantime only makes us take time answering this question instead of working on it (and other things).

If this is an urgent need for you, you have two options:

1) Implement it yourself. Everything is open source, after all. And in fact there's a working example in CesiumJS that you can use as a guide.
2) Contact our sales team to discuss if it might make sense to increase the priority of this feature by funding its development yourself. https://cesium.com/contact/#contact-sales

**Comment by kring** [comment]
To anyone reading this later, though: please do indicate your interest in this (and other) features by reacting to the top post with a 👍. Thanks!

**Comment by j9liu** [comment]
Just keeping tabs on forum posts. Came up on the forum [here](https://community.cesium.com/t/how-to-get-altitude-by-latitude-and-longitude/31290).

**Comment by LuLuEarl** [comment]
Hope to update this function in the future, it's really useful

**Comment by wangzhiyuan2021** [comment]
it's really useful

**Comment by josephsipos** [comment]
No update to this? Seems like this should be higher priority.

**Comment by kring** [comment]
We have open pull requests for this feature:
* https://github.com/CesiumGS/cesium-native/pull/783
* https://github.com/CesiumGS/cesium-unreal/pull/1421
* https://github.com/CesiumGS/cesium-unity/pull/507

If all goes to plan, the feature will be in next week's release of Cesium for Unreal and Cesium for Unity.

**Comment by josephsipos** [comment]
> We have open pull requests for this feature:
> 
> * [Add height-query function to Tileset #783](https://github.com/CesiumGS/cesium-native/pull/783)
> * [Add Unreal API for terrain height querying cesium-unreal#1421](https://github.com/CesiumGS/cesium-unreal/pull/1421)
> * [Height query API for Unity cesium-unity#507](https://github.com/CesiumGS/cesium-unity/pull/507)
> 
> If all goes to plan, the feature will be in next week's release of Cesium for Unreal and Cesium for Unity.

Oh nice! Sound great :) Much appreciated.
