### ISSUE TITLE
Allow off main thread tree traversal

### ISSUE THREAD

**Issue by ZackOfAllTrades** [CesiumGS/cesium-native#653]
I'm getting an abysmal frame rate with the new google dataset, https://developers.google.com/maps/documentation/tile/3d-tiles.
The killer is the tree traversal. Maybe because the dataset is not implicit and it has many .json files?
![image](https://github.com/CesiumGS/cesium-native/assets/13579475/d5c51c72-3b50-492d-b443-b048af1bec42)
![image](https://github.com/CesiumGS/cesium-native/assets/13579475/7828bc33-73a4-4c2a-a7c4-753e885603c0)

Doing the entire tileset update on a worker thread drastically improves performance. In my case I still process the models into Unity friendly mesh data in the worker thread on the native side but I do the resource creation after the tileset update on the main thread on the c# side.
![image](https://github.com/CesiumGS/cesium-native/assets/13579475/5b9f679d-57df-4d8f-a0f9-90b0b3eb1014)

I understand this is a big ask as it goes against the way cesium-native was designed but there is nothing stopping it from working, aside from some pesky asserts inside ReferenceCountedNonThreadSafe.h.

I bring this up to start a dialogue and to ask that we don't break the worker thread tree traversal ability with future updates.

**Comment by kring** [comment]
@ZackOfAllTrades are you saying you have your own implementation of 3D Tiles in Unity, and you're not using Cesium for Unity?

I'm very surprised by your 155ms frame time. I see far better than that with the Google tileset in Cesium for Unity, and I have an absolute potato of a GPU.

As far as thread safety, cesium-native itself doesn't care what thread you run the `updateView` on. But it does require that you always run it on the same thread and that the "main thread" parts of resource prep happen on that same thread. If you're violating those rules, you're likely to run into race conditions and undefined behavior eventually, even if it appears to work most of the time.

**Comment by timoore** [comment]
> I'm very surprised by your 155ms frame time. I see far better than that with the Google tileset in Cesium for Unity, and I have an absolute potato of a GPU.

Here's to potato GPUs! Cesium-native runs runs nicely on an integrated GPU (AMD Renoir) that's nothing special.

> 
> As far as thread safety, cesium-native itself doesn't care what thread you run the `updateView` on. But it does require that you always run it on the same thread and that the "main thread" parts of resource prep happen on that same thread. If you're violating those rules, you're likely to run into race conditions and undefined behavior eventually, even if it appears to work most of the time.

This is interesting. vsgCs could do all of the prep in a "worker" thread and in fact has to do extra work because the Tile object isn't passed to the worker thread functions. Even though the Cesium main thread does not need to be the graphics engine main thread, I'm not sure I can do much better as long as there is only one main thread, and updateViews is called from it.

**Comment by ZackOfAllTrades** [comment]
Sorry I was not clear, the drop in frame rate was not because I was GPU bound, running through the tilesetUpdate was taking 16ms on a debug build in editor, I will close this out as I have not done enough research and comparisons to justify any action, but my main takeaway is you can do the tilesetUpdate on a worker thread, even if you do nothing in the prepareInMainThread the update still takes time to run through the tree and do its comparisons.
If you run the update and get the result asynchronously that result is good and no tile will be deleted until you run the update again. So at this time I can run through all the tile pointers in the result, create my resources and render them knowing that all tile pointers are safe.
So a sample async Update method would look something like.

```csharp
private async void Update(){
           ViewState viewState = CalculateViewState();
            foreach (var tileset in tilesets)
            {
                if (tileset.IsUpdating || !tileset.IsActive)
                    continue;

                tileset.IsUpdating = true;
                TilesetUpdateResult updateResult = await tileset.UpdateTilesetAsync(viewState); // update on worker thread
                RenderTileset(tileset, updateResult); // use the result to create gameobjects on main thread
                tileset.IsUpdating = false;
            }
}
```
