### ISSUE TITLE
stop treating failed tiles as renderable

### ISSUE THREAD

**Issue by ZackOfAllTrades** [CesiumGS/cesium-native#657]
https://github.com/CesiumGS/cesium-native/commit/b8f95de5bd15d04c5a5c1a03c902ebd8cd937b5b#:~:text=if%20(getState()%20%3D%3D%20TileLoadState%3A%3AFailed,%7D

I'm curious about why we say a tile is renderable when it failed to load. It seems to do with the logic of additive tiles and their parent but even in that case, I feel like this function should tell the "truth" and logic elsewhere should change. 

With replacement, if the client goes offline or something happens with the server this causes the experience to break down and holes to appear.

At first I thought this change was just to pass a test case but it seems intentional 
![image](https://github.com/CesiumGS/cesium-native/assets/13579475/2cd5d32e-6492-4741-8656-749ecabe766d)

**Comment by kring** [comment]
Well, when a tile fails, which do you prefer? If we treat it has renderable, we render a hole, yes. But if we instead treat it as not loaded yet, we'll stop other tiles - perhaps an entire subtree - from loading as well. Is that better? I don't think so. Representing failed requests with blank spots in the data seems fairly reasonable to me. A mechanism to retry a couple times first might be nice, though.

**Comment by ZackOfAllTrades** [comment]
Thank you for the clarity! That's a tough one. If you loose wifi it is most
likely not coming back anytime soon, in that case you won't get any subtree
either. The other case where you would want to render an empty tile, is
when a single tile missed, this actually seems more rare to me. I think for
my use case where loosing wifi is a good possibility, I would rather have a
lower quality map than holes, but I can fork to do that. Thanks for the
explanation!
