### ISSUE TITLE
Will cesium-native support dynamic loading logic in Tileset's updateView when using impicit tiling data?

### ISSUE THREAD

**Issue by Mark930209** [CesiumGS/cesium-native#661]
I see that by now, in Tileset.cpp, "updateView" function still need to traverse all child nodes to detect which tile can be pushed into loadQueue. Is there any possibility that we find satified tiles directly by transform frustum space into geospatial space?    <br>From my perspective, implicit tiling mechanism support random access of tiles, in other words, we can compute which tiles to load when we get geospatial space.

**Comment by kring** [comment]
It might be possible, but it's definitely not trivial. Are you just trying to reduce the CPU time taken by `updateView`? Or do you have another motivation for wanting to do this?

**Comment by Mark930209** [comment]
In some cases, we need to deal with a very large geographical spatial scene, so we subdivide this scene into many levels and child nodes by quadtree/octree. After that, we want to reduce traversal time( CPU time) and directly compute which tiles can be loaded. I am motivated by some 2D GIS data format loading theories like WMTS or TMS. I think that could be faster than simple traversal.

**Comment by kring** [comment]
Cesium World Terrain is measured in terabytes, and Google's new 3D Tiles dataset is probably measured in petabytes. They both have many millions if not billions of tiles. The current selection algorithm is able to copy with it quite well.

So overall I see direct tile computation as an optimization, and probably not one with a great return on investment compared to other optimizations we can do.

Keep in mind that in 2D, we can just compute a "level" for the current zoom, and then it's trivial to figure out which tiles fall in the view rectangle at that level. In 3D, it's not so simple. Different parts of the scene will have different levels. Computing the intersection of a bounding region with a view frustum is pretty tricky, and even after you solve that, using that to analytically compute which of a set of bounding regions is in the view frustum - without testing each one - is harder still.

If you're really keen, though, it can probably be prototyped externally. Come up with the algorithm for determining the appropriate tiles (accounting for view frustum and SSE) to select from an implicit tileset. Measure how long that takes versus the time cesium-native takes to walk the tile tree. If it's a big win, the next step is to figure out how to integrate it into cesium-native.

**Comment by Mark930209** [comment]
kring, thanks a lot for your reply and advice. Your reply dispelled the doubts in my mind very well.
