### ISSUE TITLE
Reading an area and extracting data

### ISSUE THREAD

**Issue by DorPop** [CesiumGS/cesium-native#670]
Hey!
I'm trying to understand how to read an area defined by Lat-Long points and extracting data from it, height for example.
As I saw in TestTilesetReader, I can only read json for this action.
Is there a different file type the library can read and extract info from or I'm limited to json?
Thanks for the help!

**Comment by kring** [comment]
I'm not quite sure what you're asking. Can you explain a bit more about what you're trying to achieve?

**Comment by azrogers** [comment]
Closing since it's been nearly a year without a response.
