### ISSUE TITLE
documentation missing multiple headers

### ISSUE THREAD

**Issue by mattelser** [CesiumGS/cesium-native#672]
Going through the documentation that doxygen builds, at least a few classes in the `CesiumGltf` namespace are missing, but the headers exist and have doxygen-style comments. Notably `Model` and `NamedObject` (which do not appear to be generated by `generate-classes`) are in the docs, but `Mesh` and `MeshPrimitive` are not (which are generated). Is it possible that headers generated by `generate-classes` are not making their way into some doxygen related config?

**Comment by kring** [comment]
Yep, the generated include directories are probably missing from there:
https://github.com/CesiumGS/cesium-native/blob/main/doc/CMakeLists.txt
