### ISSUE TITLE
Have a cookies parameter in the pRequest? The code snippet below will throw a 403 error if you don't submit a cookies. 

### ISSUE THREAD

**Issue by veyvin** [CesiumGS/cesium-native#681]
import requests

url2 = "http://t6.tianditu.com/DataServer?T=img_w&x=3&y=1&l=2&tk=05093c0e36be0186ad13f6932e7a2be7"

cookies = {
    "HWWAFSESID": "46b47823c75d40bfa6",
    "HWWAFSESTIME": "1688638937327"
}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
}

response = requests.get(url2, headers=headers, cookies=cookies)

print(response.status_code)

if response.status_code == 200:
    with open("ewewewewewewee.jpg", 'wb') as file:
        file.write(response.content)
    print("图片下载成功！")
else:
    print("下载失败，错误代码:", response.status_code)

**Comment by veyvin** [comment]
![Screenshot 2023-07-07 133314](https://github.com/CesiumGS/cesium-native/assets/6776758/bbddd9cc-20bb-4d75-9af9-836539ad0688)

**Comment by kring** [comment]
cesium-native already allows HTTP headers to be specified. Cookies are just a particular HTTP header.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
