### ISSUE TITLE
Add support for EXT_meshopt_compression

### ISSUE THREAD

**Issue by wen-bing** [CesiumGS/cesium-native#685]
Gltf with EXT_meshopt_compression cannot be loaded in UE, as mesh data compressed through EXT_meshopt_compression by gltfpack. However CesiumJS has a meshopt_decoder module to decode the compressed data in buffer, so same Gltf can be loaded in CesiumJS. 

Is there any plan to add this kind decoder?

**Comment by kring** [comment]
Yes, we're actively working on this right now. See also CesiumGS/cesium-unreal#515.
