### ISSUE TITLE
Consider adding Listener mechanisms

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#74]
This has low priority\*, but we might want to talk about this at some point:

There are, very broadly speaking, some elements and structures that may undergo modifications, in a way that makes it necessary (or at least beneficial) to have the option to be *informed* about these changes. 

One very specific and concrete example here is the [`Camera`](https://github.com/CesiumGS/cesium-native/blob/master/Cesium3DTiles/include/Cesium3DTiles/Camera.h). It has several functions like `updatePositionAndOrientation` and `updateViewParameters` that modify the internal state. Right now, it is not possible to detect such modifications.

I tried to have a look at how the Camera is handled in `cesium-unreal`. There is quite some code involved that I still have to wrap my head around, but from an attempt to "zoom" into the place where the actual camera is used, it *appears* to be that in [`ACesium3DTileset::Tick`](https://github.com/CesiumGS/cesium-unreal/blob/4ebadd83864048bcd8beb68655bace2af8ea1219/Source/Cesium/Private/ACesium3DTileset.cpp#L543), a new Cesium camera is created from the state of the Unreal *Camera* and the unreal *Viewport*. This camera is then passed to the `Tileset::updateView` function. With this pattern, it is not necessary to detect changes, but it is *very* specific for Unreal (and may even depend on `bCanEverTick` being set, deciding whether `Tick` is called in each frame...). 

From an Unreal-agnostic, high-level viewpoint, one could consider to have something like 

    camera.addListener([]() { renderBecauseCameraChanged(); });

More generally, being able to be informed about state changes can be beneficial for other classes as well. This may refer to direct, *functional* use-cases (like the camera changes that may trigger a rendering), but also to things like logging, roughly as in

    tileset.addListener([] (Info &info) { log("{} tiles loaded, take one down and pass it around", info.numTiles) });

Whether or not (and how) such structures should be added is open for debate. The `Camera` was the class that essentially triggered this thought. It might be the only class where this could make sense at the moment.

---

\* It has low priority, because such a listener mechanism can always be added in a later release. One exception is when there already is a callback mechanism, as in `something.bind(callback)`, where one would have to essentially consider allowing "*multiple* callbacks", as in `something.addListener(callback); something.addListener(anotherOneThatShouldAlsoBeCalled); `.

**Comment by kring** [comment]
I'm closing this because I don't think there's anything actionable here. We've concluded that we don't need listeners for the `ViewState` (the new name for what was called `Camera` when this issue was written). We may or may not want listeners for other things in the future, but we don't need this issue to remind us to do that.
