### ISSUE TITLE
Add support for a smooth/ellipsoid terrain model

### ISSUE THREAD

**Issue by jianxiao1754** [CesiumGS/cesium-native#740]
I add a Cesium3DTileset with "Cesium World Terrain + Bing Maps Aerial imagery", then I replace the Cesium ion Raster Overlay  component of the newly added Cesium3DTileset Actor with CesiumTileMapServiceRasterOverlay component, and set the CesiumTileMapServiceRasterOverlay component's url point to my **local tms server**, so far it woks as expected. But when I disconnect the network( I need to work offline), it can't load any tile maps. The Output Log panel shows an error as 

**"LogCesium: Error: [2021-05-09 10:52:10.619] [error] [Tileset.cpp:142] Received status code 401 for asset response https://api.cesium.com/v1/assets/0/endpoint",** 

I guess that the Cesium3DTileset need to load the tileset.json, then the CesiumTileMapServiceRasterOverlay will work. But how can I just use  the CesiumTileMapServiceRasterOverlay offline without the need to load any tileset.json, because I don't need any tilesets like terrain or 3D models.

**Comment by j9liu** [comment]
Closed by #908
