### ISSUE TITLE
About the 3d-tiles-generator branch

### ISSUE THREAD

**Issue by newpeople123** [CesiumGS/cesium-native#745]
Is the function of the 3d-tiles-generator branch to generate 3dtiles? How to compile? How to test it?

**Comment by newpeople123** [comment]
Yes, this image is a png, but loading this png in osgEarth and then exporting it to webp format fails

**Comment by newpeople123** [comment]
In other words, the write method of the webp plug-in does not support grayscale images well.

**Comment by lilleyse** [comment]
@newpeople123 that's an old branch that eventually became the `Cesium3DTilesWriter` library. Just be aware that its scope is limited to tileset.json serialization.

If you're looking to convert data to 3D Tiles you might have better luck with some of the resource here: https://github.com/CesiumGS/3d-tiles/blob/main/RESOURCES.md.

If you have other questions, let's move this discussion to the [Cesium Forum](https://community.cesium.com/). We use GitHub for bugs and feature requests.
