### ISSUE TITLE
Doesn't build with installed Vulkan on VS2019 ?

### ISSUE THREAD

**Issue by remoe** [CesiumGS/cesium-native#784]
The current github action to build cesium-native with VS2019 doesn't include Vulkan SDK:

```-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")```

Found following build issue:

```
  C:\Windows\System32\bash.exe' is not recognized as an internal or external command,
```

[KTX-Software](https://github.com/KhronosGroup/KTX-Software) "Generating VkFormat-related source files"

**Comment by kring** [comment]
I don't quite understand the problem. What are you trying to do? What is this problem preventing you from doing?

**Comment by remoe** [comment]
I tried to build cesium-native on Windows x64 / VS2019.

i would only mention that it doesn't compile with an installed VulkanSDK on default location. find_package for CMake find this VulkanSDK and build it with Vulkan support. And this fails.

**Comment by remoe** [comment]
Yes, I understand. However, when one compiles it on a Windows system with the VulkanSDK installed and the VULKAN_SDK environment variable set, it doesn’t build.
This could be an issue when one compile other SDK's *with* VulkanSDK. But it's not a bug of cesium-native build.

**Comment by remoe** [comment]
This issue could be a hint for someone other who has this as well.
