### ISSUE TITLE
load and parse 3dtiles error

### ISSUE THREAD

**Issue by arvrschool** [CesiumGS/cesium-native#788]
I have printed some logs in `TilesetJsonLoader.cpp/parseExternalTilesetInWorkerThread` method, and I found some strange things, codes like below:
`const auto& tileUrl = pCompletedRequest->url();
std::cout << "tileUrl = " << tileUrl << std::endl;
`
the print message is below:
[2024-01-07 14:02:59.372] [error] [TilesetJsonLoader.cpp:698] Error when parsing tileset JSON, error code 1 at byte offset 0
tileUrl = xxxxx/Tile_+010_+011_L18_000.b3dm:0

In my opinion, there shouldn't be b3dm files here, they should all be JSON files. So i am confusing about that, but i do not know what's the problem?? 
by the way, my 3dtiles file is local.

**Comment by kring** [comment]
That does seem odd, but it depends on your tileset. cesium-native doesn't identify a b3dm by file extension, it identifies it by content. So if the b3dm is corrupt (or compressed, perhaps?) and doesn't have the expected four identifying bytes at the start (`b3dm`), then it won't be identified as a b3dm. External tileset is kind of the fallback when the file doesn't appear to be anything else.

**Comment by j9liu** [comment]
@arvrschool are you still experiencing trouble with this issue? If not, or if this thread doesn't get an update, we'll close it.

**Comment by arvrschool** [comment]
Nope. But I will check the data refer to CesiumforUnity3d.

**Comment by jsoulier** [comment]
Hello, I think I'm having the same issue. I'm passing the URL: https://raw.githubusercontent.com/CesiumGS/3d-tiles-samples/main/1.0/TilesetWithDiscreteLOD/tileset.json

The error I get is:
```
[2025-07-08 23:17:51.661] [error] [TilesetJsonLoader.cpp:776] Error when parsing tileset JSON, error code Invalid value. at byte offset 0
```

It tried loading the b3dm as JSON which of course failed (attempted URL as follows)
```
[2025-07-08 23:17:51.661] [error] [TilesetJsonLoader.cpp:770] https://raw.githubusercontent.com/CesiumGS/3d-tiles-samples/main/1.0/TilesetWithDiscreteLOD/dragon_low.b3dm
```

**Comment by timoore** [comment]
> Hello, I think I'm having the same issue. I'm passing the following URL to the Tileset: https://raw.githubusercontent.com/CesiumGS/3d-tiles-samples/main/1.0/TilesetWithDiscreteLOD/tileset.json
> 
> The error I get is:
> 
> ```
> [2025-07-08 23:17:51.661] [error] [TilesetJsonLoader.cpp:776] Error when parsing tileset JSON, error code Invalid value. at byte offset 0
> ```
> 
> It tried loading the b3dm as JSON which of course failed (attempted URL as follows)
> 
> ```
> [2025-07-08 23:17:51.661] [error] [TilesetJsonLoader.cpp:770] https://raw.githubusercontent.com/CesiumGS/3d-tiles-samples/main/1.0/TilesetWithDiscreteLOD/dragon_low.b3dm
> ```
> 
> Also happens if I clone the samples and load them locally

This works for me without any problems in a sample application (vsgCs using Cesium Native v0.48.0). Can you give more information about what you are doing (version of Cesium Native, application, etc.)? If I were you I might start looking for writes out of bounds, using freed memory, unthreadsafe things, etc.

**Comment by jsoulier** [comment]
Yep I can give more information but my current setup is pretty minimal.

```c++
static bool InitCesium(int argc, char** argv)
{
    std::string url;
    if (argc > 1)
    {
        url = argv[1];
    }
    else
    {
        url = "https://raw.githubusercontent.com/CesiumGS/3d-tiles-samples/main/1.0/TilesetWithDiscreteLOD/tileset.json";
    }
    Cesium3DTilesSelection::TilesetExternals externals{
        std::make_shared<CesiumCurl::CurlAssetAccessor>(),
        std::make_shared<PrepareRendererResources>(),
        CesiumAsync::AsyncSystem{std::make_shared<TaskProcessor>()}};
    tileset = new Cesium3DTilesSelection::Tileset(externals, url);
    return true;
}
```

I'm using the built-in `CurlAssetAccessor` using latest cesium-native. From there I'm just updating the default view group and calling load tiles. I'll take a look later at the sample application and make sure I'm not doing anything wrong. Thanks

**Comment by kring** [comment]
@jsoulier ah this is unfortunately a common problem! You need to call `registerAllTileContentTypes()` (declared in `Cesium3DTilesContent/registerAllTileContentTypes.h`) before constructing a `Tileset`.

**Comment by timoore** [comment]
Ack, of course! I should have recognized this.
