### ISSUE TITLE
Make #includes match C++ Core Guidelines

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#80]
There currently are some subtle inconsistencies regarding `include` directives. Specifically, the pattern of brackets/quotes for `<system_includes>` and `"own_includes"` is not applied consistently. The relevant comment that summarizes this is at https://github.com/CesiumGS/cesium-native/pull/56#issuecomment-745063988 

This should be fixed, preferably in one, dedicated cleanup step.

**Comment by kring** [comment]
I've changed the title to reflect the fact that the action here is to move cesium-native to the include strategy recommended in the C++ Core Guidelines: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf12-prefer-the-quoted-form-of-include-for-files-relative-to-the-including-file-and-the-angle-bracket-form-everywhere-else

More detail here: https://github.com/CesiumGS/cesium-native/pull/56#issuecomment-745063988
And here: https://github.com/CesiumGS/cesium-native/pull/56#discussion_r542526356

**Comment by kring** [comment]
We've now done this, more or less. We should write issues for any remaining issues as we find them (or just fix them), but we can close this issue.
