### ISSUE TITLE
Non-const `AccessorView`

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-native#839]
It would be convenient if `AccessorView` had a non-const `[]` operator so you could write values to the accessor.

**Comment by kring** [comment]
It's a separate class, `AccessorWriter`: https://github.com/CesiumGS/cesium-native/blob/main/CesiumGltf/include/CesiumGltf/AccessorWriter.h

**Comment by lilleyse** [comment]
Ah, thanks. I opened a PR to make it easier to construct an `AccessorWriter` if you already have an `AccessorView`: https://github.com/CesiumGS/cesium-native/pull/840
