### ISSUE TITLE
WebASM available yet ?

### ISSUE THREAD

**Issue by BararDiHoumes** [CesiumGS/cesium-native#843]
Hello dear devs.
I wonder if there is a WebASM compiled CesiumJS which is out to be used, and eventually faster than the JS version ?

**Comment by azrogers** [comment]
Hi @BararDiHoumes! We don't currently have a WebAssembly release of Cesium Native, but it's been on our radar for some time now. Previous discussion can be found in #76. If you'd like to help us investigate this possibility, that issue would be the place to record what you discover!
