### ISSUE TITLE
Error LNK2005: ZSTD_getErrorCode already defined in ktxd.lib(zstd.obj)

### ISSUE THREAD

**Issue by ComradeMashkov** [CesiumGS/cesium-native#885]
Commit: bbe581bd

When trying to build cesium-native with Visual Studio 17 2022 generator at the last stage I get the following erro: 
```bash
zstd.lib(zstd.dll) : error LNK2005: ZSTD_getErrorCode already defined in ktxd.lib(zstd.obj)
```

How can I fix this error and what is the reason for this error to appear?

**Comment by kring** [comment]
It's hard to say. That commit built successfully with VS2022 on our CI system:
https://github.com/CesiumGS/cesium-native/actions/runs/9031817639/job/24818805811

Is this while building cesium-native itself (perhaps linking the tests?), or while linking it into your own project?

It'll probably help to see the whole build log.

**Comment by j9liu** [comment]
@ComradeMashkov it's been a while since this issue was opened, so I'm going to close it for housekeeping purposes. If this is still an issue for you, please reopen with the information that Kevin requested above. Thank you!
