### ISSUE TITLE
Missing `ellipsoid` parameter

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-native#953]
An ellipsoid should get passed to `BoundingRegion` here:

https://github.com/CesiumGS/cesium-native/blob/31e93ac2992eeac7600357710dc50b7c70d54b85/Cesium3DTilesSelection/src/TilesetContentManager.cpp#L154-L157

Caught while compiling with `CESIUM_DISABLE_DEFAULT_ELLIPSOID`

**Comment by azrogers** [comment]
Good catch! I'll make a PR to fix this. Perhaps we should be building for CI with `CESIUM_DISABLE_DEFAULT_ELLIPSOID` to catch bugs like this?

**Comment by j9liu** [comment]
Closing since #956 was merged.
